--create table physicians (
--	name VARCHAR(50),
--	specialty VARCHAR(50),
--	licence_number VARCHAR(20),
--	hospital_id INT
--);

insert into physicians (name, specialty, licence_number, hospital_id) values ('Shurlocke Pods', 'Assessment Center', '54.110.113.80', 11);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Chad MacColgan', 'Solid Oxide Fuel Cells', '245.135.192.50', 13);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Hunt Lattie', 'Drilling', '137.154.20.222', 10);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Timmi Rown', 'SDTM', '6.250.85.6', 1);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Aryn Cossor', 'Zephyr', '79.123.222.10', 3);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Cornell Agglio', 'XRF', '55.240.55.120', 9);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Keelia Cock', 'HMIs', '80.163.139.85', 6);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Bernarr Marushak', 'Iyengar Yoga', '192.206.45.231', 1);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Hilly Lukasen', 'dsPIC', '111.85.249.130', 5);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Krissy Feares', 'GBS', '74.50.122.162', 2);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Lyndy Scarborough', 'Ext JS', '210.102.32.86', 8);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Liva Lofthouse', 'XOG', '195.91.201.64', 11);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Andrey Tarrant', 'Yeast two-hybrid', '115.173.26.206', 13);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Lonna Muzzini', 'Rent to Own', '247.218.188.233', 10);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Tiphany Gehrels', 'ICP', '123.198.21.46', 7);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Honoria Hovel', 'FHA', '254.212.120.120', 8);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Wallas Puttnam', 'Urban Forestry', '192.222.2.84', 11);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Edlin Dingivan', 'Commercial Kitchen Design', '88.173.62.39', 9);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Johnna Feragh', 'FTC', '45.27.37.114', 10);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Anya Follin', 'Drafting Agreements', '230.35.240.73', 12);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Tammi Blackster', 'SDH', '125.192.95.175', 5);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Royall Jaan', 'BPO', '25.19.124.63', 12);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Mariejeanne Vere', 'Windows 7', '53.221.21.80', 2);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Dasie Ascough', 'PPP', '125.85.60.130', 7);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Kalle Jemison', 'Yardi', '206.126.63.205', 6);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Ulrick Twede', 'CPT', '49.58.247.209', 12);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Caddric Horder', 'Process Improvement', '179.235.75.213', 13);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Viva Sisselot', 'PMO', '53.99.144.62', 11);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Keriann Kirton', 'Disaster Recovery', '64.240.165.51', 6);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Hakeem Pinchen', 'RTK', '219.75.224.240', 3);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Vivyan Besemer', 'Vegetables', '56.247.177.181', 6);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Gwendolyn Draisey', 'DMR', '170.92.237.219', 3);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Francois Paskins', 'FDD', '173.57.63.176', 10);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Giulia Caudelier', 'HVAC', '87.67.112.235', 10);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Maria Giovanetti', 'ITIL Certified', '45.238.198.23', 2);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Jillayne Domenichini', 'LDS', '3.157.80.109', 12);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Todd Elfe', 'Shipbuilding', '244.10.49.120', 13);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Gabby Messingham', 'MDX', '79.221.46.160', 12);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Gwynne Chidzoy', 'Business Alliances', '12.179.146.249', 5);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Devon Darnody', 'Lymphatic Drainage', '30.126.251.116', 11);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Gusella Bradnocke', 'JMP', '188.127.142.198', 4);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Quint Sheaber', 'Zend Server', '177.62.94.45', 10);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Wilow Dorrington', 'FSC Certification', '57.86.221.83', 12);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Wilma Alderson', 'Job Analysis', '152.99.141.250', 8);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Zackariah Uttermare', 'Kinect', '82.34.107.250', 11);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Maxy Josefsohn', 'Short Sales', '160.131.146.172', 4);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Hillier Condie', 'Oil &amp; Gas Law', '238.118.83.255', 6);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Paulo Kirkebye', 'DNS Management', '65.219.85.166', 1);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Aland Espley', 'MS-DOS', '49.221.105.59', 8);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Kali Aymes', 'FTL', '139.166.72.222', 6);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Moishe Izatt', 'Time-efficient', '239.70.170.88', 4);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Eugine Memmory', 'NMLS Licensed', '215.84.102.126', 4);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Prue Tye', 'PFI', '233.156.85.161', 5);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Rupert Lewing', 'DDI', '167.232.99.180', 2);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Vanna Strutt', 'AHWD', '20.172.22.113', 6);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Trstram Tabor', 'global HCM', '35.230.239.231', 1);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Justina Layson', 'VMware Server', '173.145.156.50', 7);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Shadow Mackness', 'QAS', '125.220.209.99', 13);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Zaneta Cordsen', 'SAP PS', '240.90.122.205', 7);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Kathryne Brant', 'Dyeing', '250.69.164.112', 8);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Christabel Chewter', 'Typing', '60.95.57.95', 6);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Nesta Garfirth', 'Protein Expression', '225.69.178.59', 13);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Susanna Teasell', 'AutoCAD', '52.49.122.167', 4);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Dodie Ramstead', 'Bash', '183.139.240.219', 6);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Stoddard Beasant', 'Storage', '247.139.76.17', 4);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Madalyn Blazejewski', 'PDMS Draft', '182.221.252.69', 2);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Bee Cheal', 'Administrative Law', '112.132.141.77', 13);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Merla Heeron', 'Multi-Unit', '120.204.78.29', 10);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Shanda Marshland', 'QC Tools', '148.93.48.18', 9);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Tann Joesbury', 'GxP', '171.110.216.220', 5);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Prue Danelet', 'Ektron', '206.181.223.244', 7);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Clovis Loosemore', 'IAM', '85.19.93.19', 7);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Jess Dewhurst', 'Substance Use Disorders', '235.199.66.183', 10);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Cecilla MacClenan', 'Kaizen Blitz', '84.107.29.148', 2);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Diena Barkus', 'IRS', '162.230.195.2', 13);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Baxter McSperrin', 'Microsoft Dynamics AX', '63.244.30.94', 9);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Angele Scorer', 'Branding', '55.76.83.246', 11);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Romola Spittal', 'Scrum', '3.239.241.66', 2);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Stoddard Gealy', 'DBUnit', '248.232.134.164', 9);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Jillayne Atwill', 'Pyrolysis', '194.133.116.44', 3);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Rafaello Broseke', 'IM', '117.216.85.83', 11);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Amara Kubicka', 'CCVP', '159.239.127.236', 4);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Guilbert Avieson', 'Agility', '155.159.103.164', 6);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Yorgo Pembry', 'Cardiac Rhythm Management', '116.20.16.48', 2);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Dayle Gilliat', 'Job Analysis', '108.231.26.188', 5);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Eirena Wipper', 'Ocean Freight', '60.108.81.181', 3);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Perice McCallam', 'BPMN', '62.182.55.159', 4);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Teddy Tugwell', 'IKE', '194.67.111.133', 10);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Lidia Todd', 'Legal Assistance', '216.214.201.20', 4);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Mattie Cases', 'VB5', '168.26.58.66', 11);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Mercedes Simoni', 'CCNP Certified', '150.196.64.102', 7);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Claudie Stannas', 'Jive', '249.136.42.113', 11);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Ermina Ovize', 'Microsoft SQL Server', '248.78.178.199', 2);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Wolf Balser', 'Aluminum', '106.188.170.163', 5);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Theressa Janz', 'NLRB', '246.40.194.83', 11);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Sidonnie Wallbank', 'JSA', '118.86.176.227', 11);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Redford Rushford', 'FTTP', '184.218.92.133', 8);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Ash Noblett', 'JSTL', '31.25.7.253', 10);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Vic Mamwell', 'ATP', '11.234.133.252', 1);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Ann Fyall', 'CBT', '180.60.55.44', 3);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Sheela Crafter', 'VMS', '249.48.242.130', 9);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Henrieta Leyfield', 'DB2', '92.194.81.230', 6);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Felice Orth', 'Dual Diagnosis', '8.196.237.27', 8);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Kippie MacQuist', 'Virtual PC', '82.30.149.209', 7);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Alix Lomis', 'MTOs', '80.91.140.153', 5);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Merill Currao', 'HPLC-MS', '216.178.125.245', 2);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Galven Higgonet', 'Zuken', '51.245.196.72', 2);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Pris Ashpital', 'Judicial Review', '228.81.171.29', 3);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Rem Callis', 'Oracle BPM', '181.123.223.186', 8);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Alfredo Purviss', 'Kurzweil', '26.182.170.44', 6);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Fedora Wilton', 'Earned Value Management', '208.230.168.173', 5);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Renell Najera', 'DFSS Green Belt', '170.33.236.223', 2);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Jorgan Sculpher', 'Digital Photography', '225.18.188.98', 11);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Leigha Varley', 'Xing', '183.22.48.60', 9);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Roscoe Emps', 'Screenwriting', '122.205.173.178', 4);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Gibby Chamberlain', 'Grant Writing', '98.51.195.237', 4);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Robbie Yvens', 'Community Outreach', '184.47.142.229', 1);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Malena Lyddiatt', 'VCT', '148.133.57.27', 2);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Keslie Rew', 'PXI', '236.104.208.165', 13);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Johannes Athersmith', 'Interior Design', '252.123.8.50', 13);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Blake Pauleau', 'Smartphones', '129.17.67.104', 9);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Hort Ligoe', 'Target Identification', '246.119.122.148', 3);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Hailey Hauxwell', 'IDL', '165.90.125.166', 11);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Fayette Besemer', 'Yellow Pages', '12.194.221.187', 11);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Clair Davidovits', 'Recruitment Advertising', '87.246.249.74', 13);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Bobbe Gladdor', 'ERD', '190.74.120.164', 13);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Ludvig Dobeson', 'Urban Planning', '205.245.116.176', 6);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Gabbie Twopenny', 'Utility Billing', '84.103.136.100', 8);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Rosalind Rother', 'Econometrics', '167.71.240.68', 12);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Karel Gorrick', 'Cleaning Validation', '210.218.12.46', 5);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Maryanne Gumm', 'Rail', '230.30.39.108', 11);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Cad Deniscke', 'PFMEA', '223.181.51.123', 7);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Rubetta Kimberley', 'MDRs', '113.143.252.162', 3);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Kiersten Gribbell', 'SRAM', '137.11.211.7', 9);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Hortensia Labba', 'Force Protection', '141.77.100.175', 9);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Lanette Dinzey', 'LNA', '25.77.22.101', 1);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Zita Bartoli', 'International Shipping', '242.2.208.26', 11);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Ramon Harbertson', 'TK Solver', '126.35.54.108', 13);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Megan Kean', 'Military Justice', '23.35.98.213', 5);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Ringo Borel', 'JDBC', '104.240.39.196', 1);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Lelah Kigelman', 'Xdebug', '101.144.179.67', 9);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Stacy Simakov', 'RNA', '232.242.76.61', 9);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Shalom Ramsbottom', 'Psychiatry', '103.185.248.247', 4);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Sigrid Weblin', 'Android', '64.152.69.181', 2);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Issi Urvoy', 'Database Administration', '172.80.239.28', 8);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Florence Lailey', 'Earthquake Engineering', '4.95.251.147', 6);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Yankee Allsworth', 'GTK', '145.44.8.84', 6);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Rodolfo Bedlington', 'UK Immigration', '156.59.103.180', 13);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Sloane Haugen', 'Policy Writing', '211.152.93.122', 9);
insert into physicians (name, specialty, licence_number, hospital_id) values ('Chandler Rennix', 'CBRN', '149.88.139.162', 1);
