--create table prescriptions (
--	id INT,
--	treatment_id INT,
--	medication_name VARCHAR(50),
--	dosage DECIMAL(3,2),
--	frequency INT
--);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (1, 17, 'ACETAMINOPHEN, PSEUDOEPHEDRINE HYDROCHLORIDE, CHLORPHENIRAMINE MALEATE', 1.49, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (2, 69, 'Benzethonium chloride', 0.63, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (3, 68, 'Avobenzone, Homosalate, Octisalate, Octocrylene, and Oxybenzone', 2.99, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (4, 76, 'OCTINOXATE, OXYBENZONE', 3.23, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (5, 80, 'THROMBIN HUMAN and FIBRINOGEN', 2.19, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (6, 15, 'Estradiol', 0.38, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (7, 8, 'Nystatin', 1.26, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (8, 34, 'oxymorphone hydrochloride', 2.44, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (9, 36, 'ZINC OXIDE', 1.56, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (10, 63, 'AcetaZOLAMIDE', 2.05, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (11, 16, 'Tall Ragweed Giant', 3.55, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (12, 59, 'Isosorbide mononitrate', 3.69, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (13, 83, 'neomycin sulfate - polymyxin B sulfate', 2.39, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (14, 68, 'metoprolol tartrate', 2.61, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (15, 79, 'Perindopril Erbumine', 3.51, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (16, 49, 'risperidone', 0.06, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (17, 90, 'Metformin Hydrochloride', 0.81, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (18, 40, 'OCTINOXATE, OCTISALATE', 3.34, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (19, 19, 'Oxygen', 3.31, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (20, 80, 'OCTINOXATE, OCTOCRYLENE, OCTISALATE, and OXYBENZONE', 3.95, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (21, 38, 'Theophylline', 1.48, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (22, 9, 'Menthol and Camphor and Methyl Salicylate', 2.23, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (23, 85, 'Bacitracin Zinc, Neomycin Sulfate, and Polymyxin B Sulfate', 1.75, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (24, 95, 'Caffeine Citrate', 1.06, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (25, 29, 'Amantadine Hydrochloride', 1.12, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (26, 51, 'Fosinopril Sodium', 2.14, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (27, 41, 'WITCH HAZEL', 1.42, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (28, 52, 'Sulfur', 3.34, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (29, 49, 'Levofloxacin', 3.76, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (30, 77, 'HAMAMELIS VIRGINIANA ROOT BARK/STEM BARK', 2.66, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (31, 57, 'Salicylic Acid', 1.49, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (32, 45, 'Avobenzone 2.5%, Octinoxate 6%, Oxybenzone 3%', 2.31, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (33, 37, 'Tacrolimus', 2.91, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (34, 66, 'Baclofen', 2.85, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (35, 12, 'Bismuth Subsalicylate', 0.33, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (36, 77, 'ALCOHOL', 3.75, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (37, 82, 'Simvastatin', 1.78, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (38, 47, 'Dill', 3.99, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (39, 18, 'Octinoxate', 1.23, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (40, 70, 'Amlobenz', 1.26, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (41, 87, 'maprotiline hydrochloride', 2.36, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (42, 73, 'Duloxetine', 3.69, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (43, 22, 'PREDNISONE', 1.97, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (44, 29, 'Ribavirin', 0.49, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (45, 74, 'Arnica montana, Asclepias tuberosa, Eriodictyon californicum, Eucalyptus globulus, Lobelia inflata, Plantago major,', 3.86, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (46, 63, 'Benzocaine', 0.73, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (47, 64, 'Dimethicone and Menthol', 1.57, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (48, 28, 'povidone-iodine', 3.73, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (49, 23, 'RISPERIDONE', 0.95, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (50, 17, 'AVOBENZONE, HOMOSALATE, OCTISALATE, OCTOCRYLENE, OXYBENZONE', 1.34, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (51, 99, 'Sodium Fluoride', 1.43, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (52, 11, 'Mesquite, Prosopis juliflora', 3.27, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (53, 23, 'Acetaminophen, Dextromethorphan HBr', 3.27, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (54, 92, 'SALICYLIC ACID', 2.45, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (55, 80, 'AVOBENZONE', 1.8, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (56, 54, 'Propranolol Hydrochloride', 2.3, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (57, 54, 'POVIDONE-IODINE', 3.29, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (58, 36, 'Hydroxyzine Hydrochloride', 1.69, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (59, 37, 'HYDROXYPROLINE', 0.56, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (60, 31, 'Loratadine', 2.12, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (61, 76, 'sumatriptan succinate', 2.33, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (62, 64, 'Irbesartan', 2.78, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (63, 86, 'Cetirizine Hydrochloride', 3.82, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (64, 68, 'Goats Milk', 0.21, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (65, 39, 'Nabumentone', 1.12, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (66, 6, 'Glycopyrrolate', 3.59, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (67, 60, 'Acetaminophen', 0.76, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (68, 83, 'desmopressin acetate', 3.68, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (69, 91, 'darifenacin', 3.13, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (70, 77, 'Lorazepam', 1.21, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (71, 59, 'ALCOHOL', 1.09, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (72, 95, 'Meclizine', 0.92, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (73, 78, 'OXYGEN, NITROGEN', 2.65, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (74, 52, 'Tylenol Cough and Sore Throat', 2.98, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (75, 64, 'Olive Pollen', 2.26, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (76, 62, 'Octinoxate, Titanium Dioxide, and Zinc Oxide', 0.66, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (77, 89, 'sodium fluoride', 1.49, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (78, 41, 'ETHYL ALCOHOL', 1.38, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (79, 45, 'Bupropion Hydrochloride', 0.11, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (80, 22, 'Birch River Red', 0.56, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (81, 28, 'Acetaminophen', 3.3, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (82, 40, 'Octinoxate and Titanium dioxide', 3.07, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (83, 27, 'Camphor and Menthol', 2.45, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (84, 23, 'Aconitum Napellus, Belladonna, Echinacea, Eupatorium Perfoliatum, Gelsemium Sempervirens, Ferrum Phosphoricum, Anas Barbariae, Hepatis Et Cordis Extractum', 1.9, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (85, 3, 'valsartan', 2.83, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (86, 48, 'Menthol', 1.93, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (87, 90, 'Diphenhydramine Hydrochloride', 0.42, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (88, 60, 'Dimethicone', 0.61, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (89, 34, 'Caffeine', 2.22, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (90, 21, 'BETHANECHOL CHLORIDE', 1.57, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (91, 80, 'OCTINOXATE, ZINC OXIDE', 3.81, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (92, 54, 'Salicylic Acid', 3.18, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (93, 24, 'Cimetidine', 3.59, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (94, 16, 'Ketotifen Fumarate', 2.44, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (95, 93, 'Lithium Carbonate', 3.45, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (96, 47, 'Oxycodone and Acetaminophen', 2.95, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (97, 56, 'galantamine hydrobromide', 2.94, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (98, 38, 'Candesartan cilexetil and Hydrochlorothiazide', 1.0, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (99, 42, 'Salicylic Acid', 0.88, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (100, 44, 'Bupropion Hydrochloride', 0.38, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (101, 89, 'Piroxicam', 1.18, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (102, 13, 'Senna and Docusate Sodium', 0.17, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (103, 54, 'Titantium Dioxide', 1.24, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (104, 25, 'adenosine', 0.55, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (105, 95, 'Phenytoin Sodium', 1.71, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (106, 67, 'METOPROLOL SUCCINATE', 0.8, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (107, 6, 'Glipizide', 1.75, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (108, 92, 'naproxen sodium', 1.13, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (109, 5, 'Oxygen', 1.61, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (110, 41, 'Carbidopa and Levodopa', 3.18, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (111, 57, 'diazepam', 0.59, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (112, 48, 'BUPROPION HYDROBROMIDE', 1.27, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (113, 29, 'Octinoxate and Oxybenzone', 2.86, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (114, 70, 'DIPHENHYDRAMINE HYDROCHLORIDE', 1.11, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (115, 69, 'Rifampin', 2.88, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (116, 35, 'Gabapentin', 1.76, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (117, 18, 'Quercus gambelii', 2.51, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (118, 32, 'Octinoxate and Titanium Dioxide', 0.09, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (119, 17, 'Furosemide', 0.22, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (120, 92, 'Berberis Vulgaris, Agaricus Muscarius, Urtica Urens, Glandula Suprarenalis Bovinum, Echinacea, Atropinum Sulphuricum, Ceanothus Americanus', 3.25, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (121, 77, 'Avobenzone 2.5%, Octinoxate 6%, Oxybenzone 3%', 0.56, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (122, 13, 'dutasteride', 1.73, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (123, 50, 'Avobenzone, Oxybenzone, Octocrylene', 3.21, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (124, 62, 'Octinoxate Titanium Dioxide', 2.03, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (125, 11, '- acetaminophen, dextromethorphan hydrobromide and doxylamine succinate liquid', 0.88, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (126, 11, 'Irbesartan', 3.49, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (127, 13, 'Dimethicone', 3.55, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (128, 67, 'TOPIRAMATE', 3.4, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (129, 67, 'Chloroxylenol', 0.65, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (130, 6, 'Gabapentin', 2.35, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (131, 62, 'levothyroxine sodium', 1.25, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (132, 93, 'ETHYL ALCOHOL', 1.5, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (133, 38, 'pancrelipase', 3.1, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (134, 60, 'Hydrochlorothiazide', 3.23, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (135, 11, 'ACONITUM NAPELLUS - APIS MELLIFERA - SILVER NITRATE - EUPHRASIA STRICTA - SODIUM ARSENATE, DIBASIC, HEPTAHYDRATE -', 2.86, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (136, 37, 'Diphenhydramine hydrochloride and Phenylephrine hydrochloride', 0.01, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (137, 49, 'Tacrolimus', 2.11, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (138, 74, 'Raloxifene Hydrochloride', 0.78, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (139, 77, 'Titanium dioxide', 2.27, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (140, 43, 'Titanium Dioxide', 1.55, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (141, 47, 'Cacao Bean', 3.96, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (142, 38, 'OCTINOXATE and ZINC OXIDE', 1.69, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (143, 92, 'Triclosan', 1.95, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (144, 82, 'OCTINOXATE, TITANIUM DIOXIDE, and ZINC OXIDE', 1.05, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (145, 20, 'OCTINOXATE, TITANIUM DIOXIDE, OCTISALATE, and OXYBENZONE', 0.18, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (146, 67, 'meradimate, octinoxate, octisalate, octocrylene, oxybenzone, titanium dixoide', 0.53, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (147, 29, 'Bahia Grass', 2.26, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (148, 81, 'Esomeprazole Sodium', 2.83, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (149, 34, 'diazepam', 2.05, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (150, 1, 'Salicylic Acid', 1.59, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (151, 34, 'Ragweed. Western Ambrosia psilostachya', 0.56, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (152, 12, 'PREGABALIN', 1.5, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (153, 17, 'TITANIUM DIOXIDE, OCTINOXATE, ARBUTIN, ATRACTYLODES JAPONICA ROOT OIL', 1.44, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (154, 69, 'zolpidem tartrate', 3.06, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (155, 64, 'Bismuth subsalicylate', 0.72, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (156, 9, 'Argentum 6', 2.69, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (157, 58, 'Medicated Lip Balm Stick', 0.92, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (158, 25, 'ENALAPRIL MALEATE', 0.9, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (159, 19, 'BENZALKONIUM CHLORIDE', 3.53, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (160, 79, 'Naproxen', 2.23, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (161, 18, 'Acetaminophen, Dextromethorphan HBr, Guaifenesin, Phenylephrine HCl', 0.16, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (162, 80, 'Oxycodone and Acetaminophen', 3.98, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (163, 94, 'Ondansetron Hydrochloride', 2.19, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (164, 20, 'Oxymorphone Hydrochloride', 2.81, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (165, 21, 'AVOBENZONE, HOMOSALATE, OCTISALATE, OCTOCRYLENE', 1.53, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (166, 50, 'benzethonium chloride', 0.59, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (167, 58, 'Leucine, Phenylalanine, Lysine, Methionine, Isoleucine, Valine, Histidine, Threonine, Tryptophan, Alanine, Glycine, Arginine, Proline, Serine, Tyrosine, Sodium Acetate, Dibasic Potassium Phosphate, Ma', 1.59, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (168, 43, 'Phendimetrazine Tartrate', 2.53, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (169, 76, 'Interferon (Suis)', 3.72, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (170, 28, 'Quack Grass', 3.37, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (171, 16, 'GEMCITABINE HYDROCHLORIDE', 1.97, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (172, 10, 'ALUMINUM ZIRCONIUM TETRACHLOROHYDREX GLY', 1.88, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (173, 12, 'Avobenzone, Octisalate and Octocrylene', 2.71, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (174, 76, 'Avobenzone, Homosalate, Octisalate, Octocrylene, and Oxybenzone', 3.15, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (175, 69, 'Doxycycline Hyclate', 1.57, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (176, 11, 'nifedipine', 0.15, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (177, 71, 'Cefuroxime Axetil', 2.87, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (178, 10, 'Red Oak', 3.38, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (179, 1, 'Ginger Bergamot Natural Antibacterial Foaming', 3.0, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (180, 85, 'Tizanidine', 1.86, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (181, 63, 'Stemphylium botryosum', 3.04, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (182, 13, 'Acetaminophen and Codeine Phosphate', 3.44, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (183, 99, 'fentanyl citrate', 3.98, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (184, 94, 'Enoxaparin Sodium', 0.14, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (185, 37, 'Octinoxate, Octisalate, Oxybenzone', 1.04, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (186, 12, 'Nabumetone', 2.14, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (187, 93, 'ALUMINUM ZIRCONIUM TETRACHLOROHYDREX GLY', 3.61, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (188, 53, 'Pseudoephedrine HCl', 0.6, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (189, 18, 'Enalapril Maleate', 2.85, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (190, 87, 'bupropion hydrochloride', 3.8, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (191, 70, 'Diltiazem Hydrochloride', 1.13, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (192, 1, 'Zolpidem Tartrate', 0.09, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (193, 92, 'OCTINOXATE and TITANIUM DIOXIDE', 0.61, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (194, 91, 'CAPTOPRIL', 1.26, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (195, 73, 'SELENIUM SULFIDE', 3.33, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (196, 49, 'Fluoride', 1.02, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (197, 97, 'Pseudoephedrine HCl', 2.49, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (198, 34, 'ALCOHOL', 0.62, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (199, 89, 'Sodium Fluoride', 1.62, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (200, 48, 'Prednisone', 0.05, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (201, 52, 'DEXTROSE, SODIUM CHLORIDE, and POTASSIUM CHLORIDE', 2.08, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (202, 41, 'Bacitracin', 0.99, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (203, 64, 'oxymorphone hydrochloride', 0.44, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (204, 39, 'TOLNAFTATE', 1.67, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (205, 8, 'ACETAMINOPHEN, CHLORPHENIRAMINE MALEATE, DEXTROMETHORPHAN HYDROBROMIDE', 0.66, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (206, 27, 'ZINC OXIDE', 2.19, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (207, 94, 'Aspirin', 0.5, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (208, 44, 'Benzalkonium Chloride', 2.33, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (209, 11, 'Treatment Set TS329915', 3.13, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (210, 55, 'Alternaria tenuis', 3.56, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (211, 51, 'valacyclovir hydrochloride', 0.79, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (212, 99, 'English Walnut Meat', 2.21, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (213, 95, 'METHYL SALICYLATE, MENTHOL, CAPSAICIN', 0.72, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (214, 88, 'Pyrithione zinc', 2.03, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (215, 43, 'Hydroquinone', 3.5, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (216, 18, 'Cultivated Wheat', 3.99, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (217, 47, 'Octinoxate', 3.98, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (218, 74, 'Grapefruit', 0.4, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (219, 28, 'metformin hydrochloride', 2.94, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (220, 92, 'ADO-TRASTUZUMAB EMTANSINE', 2.87, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (221, 72, 'Antihemophilic Factor/von Willebrand Factor Complex (Human)', 1.01, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (222, 9, 'Sodium Fluoride', 2.71, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (223, 67, 'ziprasidone hydrochloride', 1.02, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (224, 55, 'ETHYL ALCOHOL', 3.04, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (225, 64, 'Allantoin', 0.06, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (226, 68, 'hydroxyzine hydrochloride', 2.53, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (227, 94, 'Hydrogen Peroxide', 3.33, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (228, 54, 'Tobramycin', 0.84, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (229, 51, 'Brompheniramine maleate, Dextromethorphan HBr, Phenylephrine HCl', 2.05, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (230, 41, 'PredniSONE', 1.92, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (231, 47, 'Pulmo Echinacea', 2.55, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (232, 82, 'Levetiracetam', 3.16, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (233, 39, 'Melaleuca Pollen', 2.94, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (234, 45, 'Allantoin', 1.31, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (235, 25, 'Lopinavir and Ritonavir', 0.87, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (236, 67, 'dimethicone, octinoxate, octisalate, oxybenzone', 1.34, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (237, 39, 'Zolmitriptan', 3.71, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (238, 67, 'Titanium Dioxide, Zinc Oxide, and Octinoxate', 0.32, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (239, 100, 'acetaminophen, chlorpheniramine maleate, dextromethorphan hydrobromide, phenylephrine hydrochloride', 0.17, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (240, 35, 'Felodipine', 2.2, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (241, 2, 'sodium phosphate', 3.4, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (242, 76, 'sildenafil citrate', 0.71, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (243, 65, 'budesonide', 0.52, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (244, 73, 'Benzalkonium Chloride', 1.06, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (245, 11, 'Acetaminophen, Chlorpheniramine maleate, and Phenylephrine Hydrochloride', 2.38, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (246, 83, 'Avobenzone, Octisalate and Octocrylene', 2.95, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (247, 23, 'Insulin human', 0.19, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (248, 81, 'Furosemide', 3.03, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (249, 22, 'OXYGEN', 2.04, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (250, 36, 'topiramate', 1.92, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (251, 86, 'tetrahydrozoline HCl', 1.23, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (252, 19, '.ALPHA.-KETOGLUTARIC ACID - AMBERGRIS - ANAMIRTA COCCULUS SEED - CONIUM MACULATUM FLOWERING TOP - EPINEPHRINE - FUMARIC ACID - MALIC ACID - MELATONIN - MINERAL OIL - PTERIDIUM AQUILINUM ROOT - PYRIDOX', 3.0, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (253, 58, 'Acetaminophen, Diphenhydramine HCl', 3.85, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (254, 71, 'ammonium lactate', 1.8, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (255, 73, 'ezetimibe and simvastatin', 1.06, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (256, 26, 'diphenhydramine hydrochloride', 3.53, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (257, 47, 'Levothyroxine Sodium', 0.86, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (258, 79, 'Loratadine, Pseudoephedrine', 3.49, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (259, 3, 'Natural Progesterone', 3.12, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (260, 71, 'METHYL SALICYLATE', 2.76, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (261, 65, 'Quetiapine fumarate', 1.96, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (262, 59, 'ezetimibe and simvastatin', 3.63, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (263, 13, 'GLYCERIN', 1.44, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (264, 25, 'Nefazodone Hydrochloride', 2.46, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (265, 41, 'Allantoin', 0.09, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (266, 57, 'AVOBENZONE, OCTINOXATE, and OXYBENZONE', 2.38, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (267, 21, 'Alprazolam', 3.62, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (268, 86, 'Nicotine Polacrilex', 1.74, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (269, 93, 'Medicated Corn Removers', 1.52, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (270, 32, 'Triclosan', 3.92, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (271, 73, 'topiramate', 3.1, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (272, 75, 'Acetaminophen, Aspirin and caffeine', 1.94, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (273, 78, 'OCTINOXATE and OXYBENZONE', 0.67, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (274, 59, 'Bryonia, Ruta graveolens, Bellis perennis, Argentum metallicum', 1.91, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (275, 97, 'Ceftazidime', 0.78, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (276, 56, 'Western White Pine', 1.51, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (277, 53, 'Galantamine', 3.51, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (278, 66, 'Quercus gambelii', 3.64, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (279, 56, 'MAGNESIUM CITRATE', 3.0, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (280, 93, 'Antimon. crud., Apis mel., Arsenicum alb., Berber. vulg., Bovista, Bryonia, Cantharis, Chelidonium majus, Croton, Dulcamara, Graphites, Histaminum hydrochloricum, Lycopodium, Mezereum , Nux vom., Petroleum, Pulex irritans, Pulsatilla, Rhus toxicodendron, Sarsaparilla, Sulphur, Echinacea, Rumex crisp., Taraxacum, Urtica ur.', 0.66, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (281, 10, 'Amantadine hydrochloride', 1.21, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (282, 53, 'TRICLOSAN', 0.7, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (283, 43, 'Aspirin', 3.41, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (284, 40, 'ETHYL ALCOHOL', 3.22, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (285, 90, 'TITANIUM DIOXIDE', 0.1, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (286, 47, 'Mirtazapine', 1.61, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (287, 99, 'Naproxen', 2.73, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (288, 43, 'Stemphylium botryosum', 1.07, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (289, 79, 'Escitalopram', 3.42, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (290, 30, 'topiramate', 1.24, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (291, 73, 'Cactus Crataegus', 2.64, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (292, 35, 'Salicylic Acid', 2.48, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (293, 93, 'Ampicillin Sodium', 2.31, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (294, 86, 'Neomycin sulfate, Polymyxin B Sulfate and Hydrocortisone', 3.86, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (295, 68, 'Fentanyl', 2.94, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (296, 10, 'Chlorpheniramine Maleate and Phenylephrine Hydrochloride', 1.88, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (297, 86, 'levofloxacin', 1.93, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (298, 71, 'NITROUS OXIDE', 0.6, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (299, 34, 'ATORVASTATIN CALCIUM', 1.38, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (300, 60, 'Methylprednisolone Sodium Succinate', 1.07, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (301, 31, 'Ibuprofen', 1.68, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (302, 89, 'Corn Grass', 0.39, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (303, 41, 'Dextroamphetamine Sulfate', 1.26, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (304, 17, 'Budesonide', 3.5, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (305, 4, 'Fexofenadine Hydrochloride', 1.38, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (306, 9, 'Trichloroacetic Acid', 1.48, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (307, 20, 'Ibuprofen', 0.41, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (308, 18, 'Omega-3 Fatty Acids, Niacin, .Alpha.-Tocopherol, Vitamin D, Lauric Acid, Vitamin A, Ascorbic Acid, Thiamine Mononitrate, Riboflavin, Pyridoxine Hydrochloride, Cyanocobalamin, Iron, Zinc, Copper, Iodine, Magnesium, and Folic Acid', 0.32, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (309, 81, 'Esomeprazole magnesium', 1.58, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (310, 27, 'acetaminophen and codeine phosphate', 1.17, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (311, 33, 'ALCOHOL', 0.23, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (312, 83, 'AVOBENZONE, OCTINOXATE', 2.28, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (313, 58, 'Acetaminophen, Diphenhydramine HCl', 0.87, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (314, 79, 'fluocinolone acetonide', 3.61, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (315, 14, 'Slash Pine', 1.13, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (316, 35, 'Ipratropium Bromide', 1.82, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (317, 46, 'carbamazepine', 0.03, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (318, 18, 'SODIUM BICARBONATE', 2.69, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (319, 97, 'Mepivacaine hydrochloride', 2.97, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (320, 55, 'Diphenhydramine HCl', 2.51, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (321, 2, 'EUCALYPTOL, MENTHOL, METHYL SALICYLATE, THYMOL', 0.27, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (322, 4, 'OXYGEN', 2.29, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (323, 86, 'Ibuprofen', 3.76, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (324, 27, 'Pseudoephedrine HCl and Tripolidine', 2.83, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (325, 51, 'Venlafaxine Hydrochloride', 1.61, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (326, 87, 'diphenhydramine hydrochloride', 0.53, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (327, 61, 'zolpidem tartrate', 1.2, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (328, 31, 'oxytocin', 1.06, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (329, 44, 'Glipizide', 2.44, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (330, 90, 'piperacillin sodium and tazobactam sodium', 3.61, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (331, 55, 'Sarothamnus Aurum', 1.83, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (332, 96, 'Menthol', 0.19, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (333, 59, 'Aspirin, Caffeine', 2.39, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (334, 53, 'Candida albicans', 3.85, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (335, 98, 'Lithium Carbonate', 2.04, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (336, 83, 'Aluminum Zirconium Tetrachlorohydrex GLY', 2.97, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (337, 98, 'Octinoxate and Titanium Dioxide', 1.31, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (338, 64, 'Octinoxate, Octisalate, Oxybenzone, and Titanium Dioxide', 2.74, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (339, 48, 'Salicylic Acid', 1.81, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (340, 30, 'Nystatin and Triamcinolone Acetonide', 1.41, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (341, 48, 'nicotine polacrilex', 1.37, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (342, 90, 'haloperidol', 2.15, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (343, 100, 'dextromethorphan HBr, doxylamine succinate', 0.58, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (344, 90, 'carvedilol', 2.92, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (345, 29, 'Pseudoephedrine Hydrochloride', 3.83, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (346, 46, 'Lovastatin', 3.04, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (347, 70, 'Erythromycin', 0.94, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (348, 91, 'Promethazine Hydrochloride', 2.74, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (349, 54, 'Benzoyl Peroxide', 2.63, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (350, 78, 'Glycopyrrolate', 1.75, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (351, 82, 'desmopressin acetate', 3.17, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (352, 83, 'Carvedilol', 3.1, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (353, 39, 'Glycopyrrolate', 1.75, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (354, 86, 'Oxygen', 0.78, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (355, 71, 'SAPROPTERIN DIHYDROCHLORIDE', 1.83, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (356, 89, 'Prednisone', 0.17, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (357, 90, 'glatiramer acetate', 3.06, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (358, 4, 'Timothy, Standardized', 1.89, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (359, 4, 'Acer rubrum', 2.4, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (360, 13, 'Polyethylene Glycol 3350, Sodium Sulfate Anhydrous, Sodium Bicarbonate, Sodium Chloride, Potassium Chloride', 0.76, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (361, 50, 'Hazelnut', 0.64, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (362, 65, 'indomethacin', 0.69, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (363, 1, 'tobramycin', 1.42, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (364, 87, 'Carvedilol', 0.08, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (365, 7, 'DEXTRAN, HYPROMELLOSE 2910', 2.44, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (366, 36, 'Nabumetone', 1.79, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (367, 45, 'AVOBENZONE, HOMOSALATE, OCTISALATE, OCTOCRYLENE, OXYBENZONE', 3.93, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (368, 3, 'Menthol', 3.61, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (369, 51, 'Sulfur and Resorcinol', 2.22, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (370, 56, 'Hydrocortisone', 2.5, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (371, 65, 'enoxaparin sodium', 0.28, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (372, 85, 'bacitracin zinc, neomycin sulfate, polymyxin b sulfate', 0.12, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (373, 75, 'Allantoin', 0.39, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (374, 14, 'Cyclobenzaprine Hydrochloride', 1.03, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (375, 43, 'OCTOCRYLENE OXYBENZONE', 0.28, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (376, 77, 'TRICLOSAN', 0.51, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (377, 98, 'Triclosan', 2.65, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (378, 32, 'Allantoin', 0.85, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (379, 100, 'Aluminum Zirconium Tetrachlorohydrex Gly', 3.63, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (380, 89, 'Thuja Occidentalis', 0.24, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (381, 90, 'CEFACLOR', 0.21, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (382, 15, 'ATORVASTATIN CALCIUM', 0.22, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (383, 16, 'Doxazosin Mesylate', 2.2, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (384, 25, 'Bismuth subsalicylate', 3.23, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (385, 23, 'PRAVASTATIN SODIUM', 0.5, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (386, 46, 'Propoxyphene Hydrochloride', 3.26, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (387, 6, 'Hydrocodone Bitatrate and Acetaminophen', 2.86, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (388, 33, 'Hydroxyzine Hydrochloride', 1.14, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (389, 21, 'METHADONE HYDROCHLORIDE', 3.59, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (390, 89, 'Sulindac', 0.42, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (391, 90, 'MENTHOL', 1.92, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (392, 80, 'Stannous Fluoride', 3.62, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (393, 92, 'Jute', 3.2, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (394, 50, 'Valacyclovir Hydrochloride', 2.72, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (395, 67, 'Lamotrigine', 0.88, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (396, 66, 'lamotrigine', 1.37, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (397, 70, 'Silver Sulfadiazine', 0.74, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (398, 79, 'Octinoxate, Octisalate, Avobenzone', 0.56, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (399, 65, 'Dicloxacillin Sodium', 0.28, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (400, 78, 'Amoxicillin', 1.36, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (401, 79, 'Tetrahydrozoline Hydrochloride', 3.68, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (402, 52, 'clindamycin hydrochloride', 2.77, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (403, 73, 'Lidocaine Hydrochloride', 3.11, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (404, 46, 'peach', 0.51, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (405, 30, 'Tolnaftate', 3.34, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (406, 73, 'Sufentanil Citrate', 3.72, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (407, 49, 'MEDROXYPROGESTERONE ACETATE', 2.33, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (408, 50, 'DEXTROSE', 2.97, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (409, 14, 'ranitidine hydrochloride', 0.38, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (410, 20, 'topiramate', 3.53, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (411, 61, 'Mineral oil, Petrolatum, Phenylephrine HCl, Shark liver oil', 2.97, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (412, 44, 'Simethicone', 0.38, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (413, 10, 'Bethanechol Chloride', 2.49, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (414, 55, 'ALLANTOIN', 1.84, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (415, 86, 'OXYBENZONE', 1.09, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (416, 82, 'oxycodone hydrochloride and acetaminophen', 0.15, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (417, 19, 'Tropicamide', 2.0, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (418, 81, 'tazobactam sodium and piperacillin sodium', 3.62, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (419, 59, 'Tramadol Hydrochloride and Acetaminophen', 3.32, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (420, 34, 'Phentermine Hydrochloride', 2.86, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (421, 7, 'Alendronate Sodium', 4.0, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (422, 77, 'ARNICA MONTANA, BELLIS PERENNIS, CHAMOMILLA, IPECACUANHA, LYCOPODIUM CLAVATUM', 0.36, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (423, 84, 'Sodium Fluoride', 1.53, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (424, 29, 'Metoclopramide Hydrochloride', 3.84, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (425, 52, 'Ibuprofen', 1.88, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (426, 40, 'ACETAMINOPHEN AND CODEINE PHOSPHATE', 0.71, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (427, 24, 'Hydrochlorothiazide', 2.06, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (428, 40, 'Metformin Hydrochloride', 1.89, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (429, 20, 'Aspirin', 0.88, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (430, 19, 'Hydrogen Peroxide', 0.89, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (431, 44, 'Bethanechol Chloride', 0.93, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (432, 85, 'Olanzapine', 3.56, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (433, 85, 'Calcium Carbonate', 2.0, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (434, 86, 'Coconut', 2.74, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (435, 71, 'Aluminum Chlorohydrate', 0.12, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (436, 29, 'Aluminum Zirconium Trichlorohydrex Gly', 2.62, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (437, 29, 'penciclovir', 1.67, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (438, 27, 'Octinoxate and titanium dioxide', 3.74, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (439, 41, 'Standardized Mite D. farinae', 0.83, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (440, 87, 'Acetaminophen, Diphenhydramine HCl', 3.0, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (441, 66, 'Rhus toxicodendron', 0.25, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (442, 22, 'Ibuprofen', 2.77, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (443, 47, 'Berberis vulgaris 3X, Lycopodium clavatum 5X, Nitricum acidum 6X, Sarsaparilla 3X', 3.62, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (444, 25, 'Losartan Potassium', 1.58, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (445, 86, 'Azelastine Hydrochloride', 0.77, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (446, 35, 'ETHYL ALCOHOL', 1.73, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (447, 94, 'PHOSPHORUS', 1.44, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (448, 49, 'Treatment Set TS347337', 1.26, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (449, 77, 'bacitracin zinc,neomycin sulfate, polymyxin b sulfate, pramoxine hcl', 3.85, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (450, 51, 'Triclosan', 2.52, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (451, 58, 'Ibuprofen', 2.74, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (452, 83, 'Isoniazid', 3.78, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (453, 85, 'Octinoxate and Titanium Dioxide', 3.76, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (454, 57, 'Levetiracetam', 2.59, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (455, 48, 'potassium chloride', 0.92, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (456, 44, 'multi vitamin/mineral supplement containing vitamin C, vitamin D, vitamin E, thiamin, riboflavin, niacin, pyridoxine, folic acid, cobalamin, biotin, pantothenic acid, selenium and zinc', 2.76, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (457, 93, 'Carvedilol', 3.55, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (458, 62, 'Chlorpheniramine maleate, Phenylephrine HCl', 3.2, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (459, 25, 'Benzalkonium Chloride', 3.22, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (460, 44, 'Levothyroxine Sodium', 0.21, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (461, 15, 'Fenofibrate', 0.04, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (462, 92, 'Acetaminophen, Dextromethorphan HBr, Doxylamine Succinate', 3.28, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (463, 68, 'SIROLIMUS', 1.66, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (464, 26, 'Quinapril', 2.57, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (465, 30, 'Amlodipine Besylate and Benazepril Hydrochloride', 1.55, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (466, 44, 'azithromycin', 3.67, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (467, 76, 'QUAZEPAM', 0.41, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (468, 39, 'PYRITHIONE ZINC', 1.12, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (469, 4, 'diphenhydramine hydrochloride', 2.19, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (470, 77, 'sildenafil citrate', 2.99, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (471, 59, 'Aurum metallicum, Aurum muriaticum natronatum, Baryta carbonica, Baryta muriatica, Calcarea flourica, Ceanothus americanus, Cholesterinum, Glonoinum, Plumbum iodatum, Strophanthus', 3.67, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (472, 99, 'ARIPIPRAZOLE', 1.8, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (473, 62, 'tramadol hydrochloride', 2.69, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (474, 49, 'Acetaminophen', 3.16, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (475, 65, 'Dextromethorphan Hbr, Guiafenesin, Phenylephrine HCl', 1.95, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (476, 24, 'Octinoxate, Octisalate, Titanium Dioxide, Zinc Oxide', 1.06, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (477, 35, 'water', 0.75, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (478, 17, 'Famotidine', 0.13, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (479, 89, 'verapamil hydrochloride', 1.31, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (480, 55, 'Nicotine Polacrilex', 2.48, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (481, 72, 'L Dopa', 3.3, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (482, 68, 'ALCOHOL', 3.04, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (483, 59, 'KETOROLAC TROMETHAMINE', 0.99, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (484, 99, 'ATORVASTATIN CALCIUM', 3.43, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (485, 68, 'calcium carbonate', 0.99, 4);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (486, 10, 'Ropinirole', 1.2, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (487, 7, 'amlodipine besylate and atorvastatin calcium', 0.89, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (488, 83, 'Amoxicillin and Clavulanate Potassium', 2.68, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (489, 2, 'Oxygen', 2.39, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (490, 100, 'Treatment Set TS334946', 2.39, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (491, 54, 'Amoxicillin and Clavulanate Potassium', 2.66, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (492, 35, 'mineral oil and white petrolatum', 1.68, 3);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (493, 89, 'Piperonyl Butoxide, Pyrethrum Extract', 0.83, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (494, 77, 'Sodium Bicarbonate', 3.94, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (495, 13, 'Amlodipine Besylate and Benazepril Hydrochloride', 1.72, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (496, 93, 'Fluconazole', 2.97, 1);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (497, 90, 'darbepoetin alfa', 2.97, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (498, 64, 'Alcohol', 1.34, 2);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (499, 10, 'Clonazepam', 1.32, 5);
insert into prescriptions (id, treatment_id, medication_name, dosage, frequency) values (500, 34, 'AVOBENZONE, HOMOSALATE, OCTISALATE, OCTOCRYLENE', 1.59, 5);
